name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: npm install

      - name: Linting
        run: npm run lint

  check-types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: npm install

      - name: Check Typing
        run: npm run check-types
