name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      
      - name: Install Packages
      - run: npm install
        
  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - run: yarn run lint
    
  check_types:
    name: Check Types
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - run: yarn run check-types
