name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [opened, edited, reopened, synchronize]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/hello-world-composite-action@v1
      - name: Linting
        run: npm run lint
